kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: cloudretro
spec:
  storageClassName: standard-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
EOF